apiVersion: v1
kind: Service
metadata:
  name: rajinikanthservice
  labels:
    name: Rajini
spec:
  selector:
    app: rajini-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008
  type: LoadBalancer